name: Q6 Caller

on:
  workflow_dispatch:

jobs:
  dev:
    name: Deploy to Dev
    uses: ./.github/workflows/q6-reusable.yml
    with:
      target_env: dev

  prod:
    name: Deploy to Prod
    needs: dev
    uses: ./.github/workflows/q6-reusable.yml
    with:
      target_env: prod
